In [6]:
import numpy as np

# The Basics

In [8]:
np_array = np.array([1,2,3,4])
print(np_array)

[1 2 3 4]


In [11]:
# 2d array
np_array_2d = np.array([[9.0, 8.0, 7.0],[6.0, 5.0, 4.0]])
print(np_array_2d)

[[9. 8. 7.]
 [6. 5. 4.]]


In [15]:
 # Get dimension
print(np_array.ndim)
print(np_array_2d.ndim)

1
2


In [18]:
# Get shape
print(np_array.shape) # it will return (4,) the size of the array because np_array is a vector
print(np_array_2d.shape)

(4,)
(2, 3)


In [22]:
# Get type
print(np_array.dtype)
print(np_array_2d.dtype)

int64
float64


In [26]:
# Get size
print(np_array.itemsize)
print(np_array_2d.itemsize)

8
8


In [28]:
# Get total size - number of elements
print(np_array.size)
print(np_array_2d.size)

4
6


# Accessing / Changing specific elements, rows, columns etc

In [32]:
np_numbers = np.array([[1,2,3,4,5,6,7], [8,9,10,11,12,13,14]])
print(np_numbers)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [35]:
# Get a specific element [r, c]
np_numbers[1, 5]

13

In [37]:
# Get a specific row
print(np_numbers[0, :])
print(np_numbers[:, 2])

[1 2 3 4 5 6 7]
[ 3 10]


In [38]:
# A little advance [startindex:endindex:stepsize]
np_numbers[0, 1:6:2]

array([2, 4, 6])

In [44]:
# 3D example
np_array_3d = np.array([[[1,2],[3,4]], [[5,6],[7,8]]])
print(np_array_3d)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [45]:
np_array_3d[0,1,1]

4

# Initializing Different Types of Array

In [47]:
# All 0s matrix
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [48]:
# All 1s matrix
np.ones((4,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [49]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [50]:
# Any other number(full_like)
np.full_like(np_array_2d, 4)

array([[4., 4., 4.],
       [4., 4., 4.]])

In [51]:
# Random decimal numbers
np.random.rand(4,2)

array([[0.13732031, 0.70727178],
       [0.05997065, 0.6080034 ],
       [0.64265078, 0.80492601],
       [0.27881732, 0.41744839]])

In [54]:
# Random integer values
np.random.randint(8,size=(3,3))

array([[1, 7, 0],
       [1, 5, 2],
       [3, 6, 0]])

In [55]:
# Identity matrix
np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [58]:
# Repeating arrays
arr = np.array([[1,2,3]])
r1 = np.repeat(arr, 3, axis=1)
print(r1)

[[1 1 1 2 2 2 3 3 3]]


# Mathematics

In [72]:
a = np.array([1,2,3,4])
a

array([1, 2, 3, 4])

In [73]:
a + 2

array([3, 4, 5, 6])

In [74]:
a - 2

array([-1,  0,  1,  2])

In [75]:
a * 2

array([2, 4, 6, 8])

In [76]:
a / 2

array([0.5, 1. , 1.5, 2. ])

In [78]:
b = np.array([1,0,1,0])
a + b

array([2, 2, 4, 4])

In [79]:
# Take the sin
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

# Linear Algebra

In [85]:
ones = np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [86]:
others = np.full((3,2), 2)
others

array([[2, 2],
       [2, 2],
       [2, 2]])

In [87]:
np.matmul(ones, others)

array([[6., 6.],
       [6., 6.]])

In [88]:
# find the determinant
c = np.identity(3)
np.linalg.det(c)

1.0

# Statistics

In [89]:
stats = np.array([[1,2,3], [4,5,6]])
stats

array([[1, 2, 3],
       [4, 5, 6]])

In [90]:
np.min(stats)

1

In [96]:
np.max(stats, axis=1) # get the max numbers in a row

array([3, 6])

In [99]:
np.sum(stats, axis=0) # sum the number in the column

array([5, 7, 9])

# Regorganizing arrays

In [101]:
before = np.array([[1,2,3,4], [5,6,7,8]])
before

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [103]:
after = before.reshape(8,1)
after

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8]])

In [105]:
# vertically stacking vectors
v1 = np.array([1,2,3,4])
v2 = np.array([5,6,7,8])

np.vstack([v1,v2,v1,v2])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [1, 2, 3, 4],
       [5, 6, 7, 8]])

In [107]:
# horizontal stack
h1 = np.ones((2,4))
h2 = np.zeros((2,2))

np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

# Miscellaneous
## Load data from file

In [115]:
file_data = np.genfromtxt('data.txt', delimiter=',')
file_data = file_data.astype('int32')
file_data

array([[  1,   2,   3,   4,   5,  23,  24,  53,  29],
       [ 32,  22,  16,  15,  13,   0,   9,   8,  78],
       [ 25,  56, 233,  57,   9,  39,  90,  99,  80]], dtype=int32)

## Boolean indexing and advanced indexing

In [117]:
file_data[file_data > 50]

array([ 53,  78,  56, 233,  57,  90,  99,  80], dtype=int32)

In [119]:
# You can index with a list in Numpy
my_list = np.array([1,2,3,4,5,6,7,8,9])
my_list[[1,2,7]]

array([2, 3, 8])

In [124]:
np.all(file_data > 50, axis=0)

array([False, False, False, False, False, False, False, False, False])